name: Bun CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: ["v1.x"]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Use Bun Version ${{ matrix.bun-version }}
        uses: antongolub/action-setup-bun@v1.12.8
        with:
          bun-version: ${{ matrix.bun-version }}
          bun-repo: 'oven-sh/bun'
      - name: Install Dependencies
        run: bun x jsr add @cross/runtime @std/assert @std/async
      - name: Install Sinon
        run: bun add sinon
      - name: Test Bun Module
        run: bun test