name: Bun CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: ["v1.x"]

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: bunx jsr add @cross/test @std/assert
      - name: Test Bun Module
        run: bun test